//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace messagerService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="messagerService.messagerSoap")]
    public interface messagerSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSingleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.SendSingleSMSResponse> SendSingleSMSAsync(messagerService.SendSingleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.GetBalanceResponse> GetBalanceAsync(messagerService.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateCredentail", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.ValidateCredentailResponse> ValidateCredentailAsync(messagerService.ValidateCredentailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPaymentHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.getPaymentHistoryResponse> getPaymentHistoryAsync(messagerService.getPaymentHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.generateReportResponse> generateReportAsync(messagerService.generateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getscheduledMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.getscheduledMessagesResponse> getscheduledMessagesAsync(messagerService.getscheduledMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessageHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.getMessageHistoryResponse> getMessageHistoryAsync(messagerService.getMessageHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<messagerService.CustomerProfileResponse> CustomerProfileAsync(messagerService.CustomerProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingleSMS", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.SendSingleSMSRequestBody Body;
        
        public SendSingleSMSRequest()
        {
        }
        
        public SendSingleSMSRequest(messagerService.SendSingleSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSingleSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mobiles;
        
        public SendSingleSMSRequestBody()
        {
        }
        
        public SendSingleSMSRequestBody(string UserName, string password, string message, string sender, string mobiles)
        {
            this.UserName = UserName;
            this.password = password;
            this.message = message;
            this.sender = sender;
            this.mobiles = mobiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingleSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.SendSingleSMSResponseBody Body;
        
        public SendSingleSMSResponse()
        {
        }
        
        public SendSingleSMSResponse(messagerService.SendSingleSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSingleSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSingleSMSResult;
        
        public SendSingleSMSResponseBody()
        {
        }
        
        public SendSingleSMSResponseBody(string SendSingleSMSResult)
        {
            this.SendSingleSMSResult = SendSingleSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.GetBalanceRequestBody Body;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(messagerService.GetBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetBalanceRequestBody()
        {
        }
        
        public GetBalanceRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.GetBalanceResponseBody Body;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(messagerService.GetBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody()
        {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCredentailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCredentail", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.ValidateCredentailRequestBody Body;
        
        public ValidateCredentailRequest()
        {
        }
        
        public ValidateCredentailRequest(messagerService.ValidateCredentailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateCredentailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateCredentailRequestBody()
        {
        }
        
        public ValidateCredentailRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCredentailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCredentailResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.ValidateCredentailResponseBody Body;
        
        public ValidateCredentailResponse()
        {
        }
        
        public ValidateCredentailResponse(messagerService.ValidateCredentailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateCredentailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateCredentailResult;
        
        public ValidateCredentailResponseBody()
        {
        }
        
        public ValidateCredentailResponseBody(string ValidateCredentailResult)
        {
            this.ValidateCredentailResult = ValidateCredentailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentHistoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentHistory", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getPaymentHistoryRequestBody Body;
        
        public getPaymentHistoryRequest()
        {
        }
        
        public getPaymentHistoryRequest(messagerService.getPaymentHistoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPaymentHistoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getPaymentHistoryRequestBody()
        {
        }
        
        public getPaymentHistoryRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getPaymentHistoryResponseBody Body;
        
        public getPaymentHistoryResponse()
        {
        }
        
        public getPaymentHistoryResponse(messagerService.getPaymentHistoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPaymentHistoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPaymentHistoryResult;
        
        public getPaymentHistoryResponseBody()
        {
        }
        
        public getPaymentHistoryResponseBody(string getPaymentHistoryResult)
        {
            this.getPaymentHistoryResult = getPaymentHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateReport", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.generateReportRequestBody Body;
        
        public generateReportRequest()
        {
        }
        
        public generateReportRequest(messagerService.generateReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generateReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public generateReportRequestBody()
        {
        }
        
        public generateReportRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.generateReportResponseBody Body;
        
        public generateReportResponse()
        {
        }
        
        public generateReportResponse(messagerService.generateReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generateReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateReportResult;
        
        public generateReportResponseBody()
        {
        }
        
        public generateReportResponseBody(string generateReportResult)
        {
            this.generateReportResult = generateReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getscheduledMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getscheduledMessages", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getscheduledMessagesRequestBody Body;
        
        public getscheduledMessagesRequest()
        {
        }
        
        public getscheduledMessagesRequest(messagerService.getscheduledMessagesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getscheduledMessagesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getscheduledMessagesRequestBody()
        {
        }
        
        public getscheduledMessagesRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getscheduledMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getscheduledMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getscheduledMessagesResponseBody Body;
        
        public getscheduledMessagesResponse()
        {
        }
        
        public getscheduledMessagesResponse(messagerService.getscheduledMessagesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getscheduledMessagesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getscheduledMessagesResult;
        
        public getscheduledMessagesResponseBody()
        {
        }
        
        public getscheduledMessagesResponseBody(string getscheduledMessagesResult)
        {
            this.getscheduledMessagesResult = getscheduledMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageHistoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageHistory", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getMessageHistoryRequestBody Body;
        
        public getMessageHistoryRequest()
        {
        }
        
        public getMessageHistoryRequest(messagerService.getMessageHistoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageHistoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getMessageHistoryRequestBody()
        {
        }
        
        public getMessageHistoryRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.getMessageHistoryResponseBody Body;
        
        public getMessageHistoryResponse()
        {
        }
        
        public getMessageHistoryResponse(messagerService.getMessageHistoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageHistoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMessageHistoryResult;
        
        public getMessageHistoryResponseBody()
        {
        }
        
        public getMessageHistoryResponseBody(string getMessageHistoryResult)
        {
            this.getMessageHistoryResult = getMessageHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerProfile", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.CustomerProfileRequestBody Body;
        
        public CustomerProfileRequest()
        {
        }
        
        public CustomerProfileRequest(messagerService.CustomerProfileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerProfileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CustomerProfileRequestBody()
        {
        }
        
        public CustomerProfileRequestBody(string UserName, string password)
        {
            this.UserName = UserName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public messagerService.CustomerProfileResponseBody Body;
        
        public CustomerProfileResponse()
        {
        }
        
        public CustomerProfileResponse(messagerService.CustomerProfileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerProfileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerProfileResult;
        
        public CustomerProfileResponseBody()
        {
        }
        
        public CustomerProfileResponseBody(string CustomerProfileResult)
        {
            this.CustomerProfileResult = CustomerProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface messagerSoapChannel : messagerService.messagerSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class messagerSoapClient : System.ServiceModel.ClientBase<messagerService.messagerSoap>, messagerService.messagerSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public messagerSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(messagerSoapClient.GetBindingForEndpoint(endpointConfiguration), messagerSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public messagerSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(messagerSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public messagerSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(messagerSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public messagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.SendSingleSMSResponse> messagerService.messagerSoap.SendSingleSMSAsync(messagerService.SendSingleSMSRequest request)
        {
            return base.Channel.SendSingleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.SendSingleSMSResponse> SendSingleSMSAsync(string UserName, string password, string message, string sender, string mobiles)
        {
            messagerService.SendSingleSMSRequest inValue = new messagerService.SendSingleSMSRequest();
            inValue.Body = new messagerService.SendSingleSMSRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.sender = sender;
            inValue.Body.mobiles = mobiles;
            return ((messagerService.messagerSoap)(this)).SendSingleSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.GetBalanceResponse> messagerService.messagerSoap.GetBalanceAsync(messagerService.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.GetBalanceResponse> GetBalanceAsync(string UserName, string password)
        {
            messagerService.GetBalanceRequest inValue = new messagerService.GetBalanceRequest();
            inValue.Body = new messagerService.GetBalanceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.ValidateCredentailResponse> messagerService.messagerSoap.ValidateCredentailAsync(messagerService.ValidateCredentailRequest request)
        {
            return base.Channel.ValidateCredentailAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.ValidateCredentailResponse> ValidateCredentailAsync(string UserName, string password)
        {
            messagerService.ValidateCredentailRequest inValue = new messagerService.ValidateCredentailRequest();
            inValue.Body = new messagerService.ValidateCredentailRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).ValidateCredentailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.getPaymentHistoryResponse> messagerService.messagerSoap.getPaymentHistoryAsync(messagerService.getPaymentHistoryRequest request)
        {
            return base.Channel.getPaymentHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.getPaymentHistoryResponse> getPaymentHistoryAsync(string UserName, string password)
        {
            messagerService.getPaymentHistoryRequest inValue = new messagerService.getPaymentHistoryRequest();
            inValue.Body = new messagerService.getPaymentHistoryRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).getPaymentHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.generateReportResponse> messagerService.messagerSoap.generateReportAsync(messagerService.generateReportRequest request)
        {
            return base.Channel.generateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.generateReportResponse> generateReportAsync(string UserName, string password)
        {
            messagerService.generateReportRequest inValue = new messagerService.generateReportRequest();
            inValue.Body = new messagerService.generateReportRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).generateReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.getscheduledMessagesResponse> messagerService.messagerSoap.getscheduledMessagesAsync(messagerService.getscheduledMessagesRequest request)
        {
            return base.Channel.getscheduledMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.getscheduledMessagesResponse> getscheduledMessagesAsync(string UserName, string password)
        {
            messagerService.getscheduledMessagesRequest inValue = new messagerService.getscheduledMessagesRequest();
            inValue.Body = new messagerService.getscheduledMessagesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).getscheduledMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.getMessageHistoryResponse> messagerService.messagerSoap.getMessageHistoryAsync(messagerService.getMessageHistoryRequest request)
        {
            return base.Channel.getMessageHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.getMessageHistoryResponse> getMessageHistoryAsync(string UserName, string password)
        {
            messagerService.getMessageHistoryRequest inValue = new messagerService.getMessageHistoryRequest();
            inValue.Body = new messagerService.getMessageHistoryRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).getMessageHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<messagerService.CustomerProfileResponse> messagerService.messagerSoap.CustomerProfileAsync(messagerService.CustomerProfileRequest request)
        {
            return base.Channel.CustomerProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<messagerService.CustomerProfileResponse> CustomerProfileAsync(string UserName, string password)
        {
            messagerService.CustomerProfileRequest inValue = new messagerService.CustomerProfileRequest();
            inValue.Body = new messagerService.CustomerProfileRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.password = password;
            return ((messagerService.messagerSoap)(this)).CustomerProfileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.messagerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.messagerSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.messagerSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://smsapi.richtravelandtours.com/messager.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.messagerSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://smsapi.richtravelandtours.com/messager.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            messagerSoap,
            
            messagerSoap12,
        }
    }
}
